FROM node:lts-alpine as builder

WORKDIR /app

COPY . .

RUN npm install

ENV NODE_ENV production
ENV REACT_APP_API http://localhost:3000

RUN npm run build


FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]